apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: opentofu-aws-asg
  title: asg OpenTofu Module
  description: Reusable AWS OpenTofu module for asg
  annotations:
    github.com/project-slug: my-org/terraform-modules
  tags:
    - opentofu
    - aws
    - infrastructure
spec:
  type: infrastructure
  lifecycle: production
  owner: platform-engineering
  system: opentofu-modules
